AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: download-fg-images

Globals:
  Function:
    Runtime: python3.8
    Handler: app.lambda_handler
    Timeout: 300
    MemorySize: 1024

Resources:

  ####### S3 Buckets #######

  # Data Buckets
  
  FgMovieDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "movies-plus-data-raw-stills"
  
  # Image Buckets

  RawStillsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "movies-plus-data-raw-stills"
  
  WebStillsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "movies-plus-data-web-stills"

  UniformStillsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "movies-plus-data-uniform-stills"

  SubImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "movies-plus-data-sub-images"

  # Vector Buckets
    


  ####### Lambda Functions #######

  GetMovieListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/get-movie-list/
      Events:
        ScheduleGetImages:
          Type: Schedule
          Properties:
            Name: MonthlyImageFetch
            Schedule: 'rate(30 days)'
            Enabled: False

  DownloadImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda-functions/download-images/
      Policies:
      - S3FullAccessPolicy:
          BucketName: "movies-plus-data-raw-stills"
      Events:
        PostImageDownload:
          Type: Api
          Properties:
            Path: /
            Method: post

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: 
      Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
