version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fg-data-process"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fv9ot1669nzf"
s3_prefix = "fg-data-process"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
